[package]
name = "drizzle_dumper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
nix = { version = "0.27", features = ["ptrace", "user"] }
procfs = { version = "0.16", default-features = false }
sha1 = "0.10"
