name: android-arm64-build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always
  ANDROID_API_LEVEL: 24

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: false

      - name: Configure Android toolchain env
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> "$GITHUB_ENV"
          TOOLCHAIN_DIR="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
          echo "AR_aarch64_linux_android=${TOOLCHAIN_DIR}/llvm-ar" >> "$GITHUB_ENV"
          echo "CC_aarch64_linux_android=${TOOLCHAIN_DIR}/aarch64-linux-android${ANDROID_API_LEVEL}-clang" >> "$GITHUB_ENV"
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=${TOOLCHAIN_DIR}/aarch64-linux-android${ANDROID_API_LEVEL}-clang" >> "$GITHUB_ENV"

      - name: Build (aarch64-linux-android)
        run: cargo build --release --target aarch64-linux-android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drizzle-dumper-android-arm64
          path: target/aarch64-linux-android/release/drizzle_dumper
